default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: eventful_development

test:
  <<: *default
  database: eventful_test

production:
  <<: *default
  database: eventful_production
  username: eventful
  password: <%= ENV["EVENTFUL_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
